#!/usr/bin/env python
import sys
import re
import os


if len(sys.argv) != 3:
    sys.exit("Za malo argumentow")

if not os.path.isdir(sys.argv[1]):
    sys.exit("Pierwszy argument nie jest katalogiem")

if not os.path.isfile(sys.argv[2]):
    sys.exit("Drugi argument nie jest plikiem")

DIR = sys.argv[1]
FILE = sys.argv[2]

utworzonyPlik = open('plik.txt','w')
def has_hidden_attribute(filepath):
    return bool(os.stat(filepath).st_file_attributes & stat.FILE_ATTRIBUTE_HIDDEN)


for root, directories, files in os.walk(DIR):
    for directory in directories:
        tmp_dir = os.path.join(root, directory)
        filesInTmpDir = os.listdir(DIR)
        liczbaPlikowUkrytych = 0
        for fil in fileInTmpDir:
            tmp_fil_in_dir = os.path.join(tmp_dir, fil)
            if has_hidden_attribute(tmp_fil_in_dir):
                liczbaPlikowUkrytych += 1
        utworzonyPlik.write(liczbaPlikowUkrytych)
    for file in files:
        tmp_file = os.path.join(root, file)
        if os.path.isfile(tmp_file):
            fullpath = os.path.join(root, file)
                    print(fullpath.replace("/", "\\"))
           
            
        

        
    



utworzonyPlik.close()
